using System;
using System.Collections.Generic;
using UnityEngine;
using Verse;
using RimWorld;

namespace Overlord
{
    /// <summary>
    /// Core GameComponent. Handles lifecycle, state sync ticking, relay connection,
    /// map rendering, and colonist bar overlay.
    /// </summary>
    public class OverlordGameComponent : GameComponent
    {
        public static OverlordGameComponent Instance { get; private set; }

        /// <summary>
        /// Short build fingerprint for the init log line: assembly version, the
        /// module MVID (regenerated by every compile, so two builds are never
        /// confused), and the DLL's write time. Lets a Player.log say exactly
        /// which binary produced it.
        /// </summary>
        private static string DescribeBuild()
        {
            try
            {
                var asm = typeof(OverlordGameComponent).Assembly;
                string mvid = asm.ManifestModule.ModuleVersionId.ToString("N").Substring(0, 8);
                string ver = asm.GetName().Version?.ToString() ?? "?";
                string built = "?";
                try
                {
                    string path = asm.Location;
                    if (!string.IsNullOrEmpty(path) && System.IO.File.Exists(path))
                        built = System.IO.File.GetLastWriteTime(path).ToString("yyyy-MM-dd HH:mm");
                }
                catch { }
                return $"v{ver} build {mvid} ({built})";
            }
            catch { return "build unknown"; }
        }

        private RelayClient relayClient;
        private EmbeddedWebServer embeddedServer;
        private MapRenderer mapRenderer;
        private ViewerManager viewerManager;
        private bool initialized;
        private readonly ThreadSafeQueue<Action> embeddedQueue = new ThreadSafeQueue<Action>();
        private readonly Queue<PortraitRequest> portraitQueue = new Queue<PortraitRequest>();
        private readonly HashSet<string> pendingPortraitKeys = new HashSet<string>();
        private readonly Dictionary<int, string> portraitCache = new Dictionary<int, string>();
        private float nextPortraitTime;

        // Item icons are static per (def, stuff) — cache permanently, no invalidation.
        // "defName" or "defName|stuffDefName" -> base64 PNG (or "" = no icon, cached
        // so we don't re-attempt a def with no uiIcon every request).
        private readonly Dictionary<string, string> iconCache = new Dictionary<string, string>();
        // Icon RENDERING (Graphics.DrawTexture + ReadPixels GPU stall + EncodeToPNG)
        // is bounded to a few per frame via this queue — rendering a whole 60-key
        // request inline stalled the streamer's game when several viewers opened
        // buy menus at once. Each queued request remembers who to answer.
        private readonly Queue<IconRequest> iconQueue = new Queue<IconRequest>();
        private readonly HashSet<string> pendingIconKeys = new HashSet<string>();
        private const int IconsRenderedPerFrame = 2;

        private class IconRequest
        {
            public string username;
            public string key;
        }

        private class PortraitRequest
        {
            public string username;
            public Pawn pawn;
            public int pawnId;
            public string key;
        }

        public OverlordGameComponent(Game game)
        {
            Instance = this;
        }

        public void Initialize()
        {
            if (initialized)
                return;

            initialized = true;
            RespawnManager.ClearCooldowns();
            if (viewerManager == null)
                viewerManager = new ViewerManager();

            var settings = OverlordMod.Settings;

            // Start relay client if URL configured
            if (!string.IsNullOrEmpty(settings.relayUrl))
            {
                relayClient = new RelayClient(settings.relayUrl, settings.hostSecret);
                relayClient.OnConnected += () =>
                {
                    LogUtil.Log("Connected to relay server");
                    SendHostCapabilities(adminOnly: true);
                    viewerManager?.SendColonistList();
                };
                relayClient.OnDisconnected += () => LogUtil.Warn("Disconnected from relay server");
                relayClient.OnMessageReceived += OnRelayMessage;
                relayClient.Connect();
            }
            else
            {
                // No relay — start embedded local server
                embeddedServer = new EmbeddedWebServer(settings.localPort);
                // Queue all embedded server callbacks to main thread
                embeddedServer.OnViewerConnected += (user, display) =>
                {
                    embeddedQueue.Enqueue(() =>
                    {
                        viewerManager.GetOrCreateSession(user, display);
                        LogUtil.Log($"Local viewer connected: {display}");
                        viewerManager.SendColonistList(user);
                        SendHostCapabilities(user);
                        viewerManager.SendPermissions(user);
                        viewerManager.SendGameInfoNow(user);
                    });
                };
                embeddedServer.OnViewerDisconnected += user =>
                {
                    embeddedQueue.Enqueue(() =>
                    {
                        viewerManager?.MarkDisconnected(user);
                        LogUtil.Log($"Local viewer disconnected: {user}");
                    });
                };
                embeddedServer.OnCommandReceived += (user, json) =>
                {
                    embeddedQueue.Enqueue(() =>
                    {
                        string type = JsonHelper.ExtractString(json, "type");
                        if (type == StateProtocol.Command || type == "command")
                            HandleCommand(json);
                        else if (type == StateProtocol.MapTransport)
                            HandleMapTransport(json);
                        else if (type == StateProtocol.RequestState || type == StateProtocol.StateResyncRequest)
                            HandleRequestState(json);
                        else if (type == StateProtocol.Assign && IsAdminMessage(json))
                            HandleAssign(json);
                        else if (type == StateProtocol.Unassign && IsAdminMessage(json))
                            HandleUnassign(json);
                        else if (type == StateProtocol.ClaimResponse && IsAdminMessage(json))
                            HandleClaimResponse(json);
                        else if (type == "chat")
                            HandleChat(json);
                    });
                };
                embeddedServer.Start();
                LogUtil.Log($"Embedded server started on port {settings.localPort}");
            }

            // Map renderer (used by both relay and embedded paths)
            mapRenderer = new MapRenderer();
            mapRenderer.Start();

            // Heal equipment trackers corrupted by the old apparel-as-Equip bug
            // (null slots suppress the pawn's tick — uncontrollable pawns) so an
            // affected save self-repairs on load instead of needing dev-mode surgery.
            try
            {
                var colonists = Find.CurrentMap?.mapPawns?.FreeColonists;
                if (colonists != null)
                {
                    foreach (var colonist in colonists)
                        PawnCommandRouter.RepairEquipmentTracker(colonist);
                }
            }
            catch { }

            RimWorldCompat.LogCapabilitiesOnce();
            // Build identity on the init line. Reviewing the 2026-08-03 play
            // session, Player.log could not answer "which DLL was actually
            // running?" — deploys landed throughout the stream and nothing in
            // the log distinguished them, so no fix could be confirmed loaded.
            // MVID changes on every compile, so this is exact, not a manual bump.
            LogUtil.Log($"Overlord initialized — {DescribeBuild()}");

            // Preserve the previous session's log before the NEXT launch destroys it.
            // RimWorld keeps only Player.log + Player-prev.log, so a crashed session's
            // log survives exactly one restart — which is why the 2026-08-04 camp crash
            // could not be diagnosed at all. See PlayerLogArchiver.
            PlayerLogArchiver.ArchivePreviousSessionLog();

            // Name any Toolkit member that failed to bind, here, once. Every reflection
            // helper in the bridge returns a plausible fallback on a miss, so without
            // this a Toolkit rename reaches the streamer as a confident wrong message
            // ("not enough coins", "chat is not connected") instead of as itself.
            TwitchToolkitBridge.VerifyToolkitBindingOnce();
        }

        // RimWorld does not call GameComponentTick while the game is paused, but
        // it does keep calling GameComponentUpdate. Everything viewer-facing
        // therefore lives on Update: with command dispatch on Tick, every queued
        // command (work priorities, schedule, gear, purchases) stalled until the
        // streamer unpaused — reported as "I have to wait for you to unpause for
        // it to change" — and viewers saw frozen pawn state alongside a map that
        // was still updating.
        public override void GameComponentTick()
        {
        }

        public override void GameComponentUpdate()
        {
            if (!initialized)
                return;

            relayClient?.ProcessQueue();
            embeddedQueue.DrainTo(action => action());
            TwitchToolkitBridge.ProcessQueuedPawnLinks();
            TwitchToolkitBridge.ProcessQueuedChatCommands(viewerManager);

            // Self-paced on realtimeSinceStartup (StateSyncIntervalSeconds), so
            // driving it from Update does not raise its rate — it just stops it
            // from freezing while paused.
            viewerManager?.Tick();

            if (viewerManager == null || mapRenderer == null)
                return;

            mapRenderer.Update(viewerManager);
            ProcessPortraitQueue();
            ProcessIconQueue();
        }

        public override void GameComponentOnGUI()
        {
            if (!initialized || viewerManager == null)
                return;

            // Only draw overlay outside of loading events
            if (Event.current.type == EventType.Repaint || Event.current.type == EventType.Layout)
                ColonistBarOverlay.Draw(viewerManager);

            ClaimAlertOverlay.Draw(this, viewerManager);
        }

        public override void ExposeData()
        {
            if (viewerManager == null)
                viewerManager = new ViewerManager();

            Scribe_Deep.Look(ref viewerManager, "viewerManager");

            if (Scribe.mode == LoadSaveMode.PostLoadInit)
            {
                if (viewerManager == null)
                    viewerManager = new ViewerManager();
            }
        }

        public void Shutdown()
        {
            mapRenderer?.Shutdown();
            mapRenderer = null;

            embeddedServer?.Stop();
            embeddedServer = null;

            relayClient?.Disconnect();
            relayClient = null;

            portraitQueue.Clear();
            pendingPortraitKeys.Clear();
            portraitCache.Clear();
            iconQueue.Clear();
            pendingIconKeys.Clear();
            // iconCache is keyed by defName+stuff (not thingIDNumber), so it is
            // stable across save loads and intentionally NOT cleared here.
            // Static per-pawn state must not leak across save loads — thingIDNumbers
            // are reused between saves.
            PawnCommandRouter.ClearAutoDraftState();
            ArmoryCatalog.ClearClaims();
            PawnStateSerializer.ClearSignatureCaches();

            initialized = false;
            Instance = null;
            LogUtil.Log("Overlord shut down");
        }

        private void OnRelayMessage(string json)
        {
            try
            {
                string type = JsonHelper.ExtractString(json, "type");
                if (type == null) return;

                switch (type)
                {
                    case StateProtocol.ViewerJoined:   HandleViewerJoined(json); break;
                    case StateProtocol.ViewerLeft:     HandleViewerLeft(json);   break;
                    case StateProtocol.Command:        HandleCommand(json);      break;
                    case StateProtocol.MapTransport:   HandleMapTransport(json); break;
                    // These four bypass PawnCommandRouter entirely, so its command
                    // cooldown never applied, and the relay throttles nothing except
                    // context_menu. Each is real main-thread work — request_state alone
                    // re-serializes the pawn, rebuilds permissions, queues a portrait
                    // render, and sends a tactical-map snapshot + resource readout.
                    // A per-viewer, per-type floor is the backstop that does not depend
                    // on any client behaving.
                    case StateProtocol.RequestState:
                    case StateProtocol.StateResyncRequest:
                        if (ShouldServeRequest(type, JsonHelper.ExtractLastString(json, "username"), 30))
                            HandleRequestState(json);
                        break;
                    case StateProtocol.RequestArmory:
                        if (ShouldServeRequest(type, JsonHelper.ExtractLastString(json, "username"), 30))
                            HandleRequestArmory(json);
                        break;
                    case StateProtocol.RequestIcons:
                        if (ShouldServeRequest(type, JsonHelper.ExtractLastString(json, "username"), 30))
                            HandleRequestIcons(json);
                        break;
                    case StateProtocol.RequestRoster:
                        if (ShouldServeRequest(type, JsonHelper.ExtractLastString(json, "username"), 60))
                            HandleRequestRoster(json);
                        break;
                    case StateProtocol.Assign:         if (IsAdminMessage(json)) HandleAssign(json);       break;
                    case StateProtocol.Unassign:       if (IsAdminMessage(json)) HandleUnassign(json);     break;
                    case StateProtocol.ClaimResponse:  if (IsAdminMessage(json)) HandleClaimResponse(json); break;
                    case "chat":                       HandleChat(json);         break;
                    case "request_colonist_list":
                        // Host-side floor. A client stuck in a reconnect loop re-requests
                        // forever and each rebuild is main-thread work (relay logs
                        // 2026-08-04: one viewer every ~4.7s, indefinitely). The client
                        // debounce cannot be trusted — a stale build ignores it — so the
                        // host enforces its own minimum regardless of what asks.
                        if (!ShouldServeColonistList(JsonHelper.ExtractLastString(json, "username")))
                            break;
                        viewerManager?.SendColonistList(JsonHelper.ExtractLastString(json, "username"));
                        // Admin connect sends this with source=admin: replay pending
                        // claims so a freshly opened admin page doesn't show "no
                        // claims" while viewers wait. Game state is the source of
                        // truth; admin.html upserts, so replays are idempotent.
                        if (JsonHelper.ExtractLastString(json, "source") == "admin" && viewerManager != null)
                        {
                            foreach (var claim in viewerManager.PendingClaims)
                            {
                                relayClient?.Broadcast(new Dictionary<string, object>
                                {
                                    ["type"] = StateProtocol.ClaimRequest,
                                    ["username"] = claim.username,
                                    ["displayName"] = claim.displayName,
                                    ["pawnId"] = claim.pawnId,
                                    ["pawnName"] = claim.pawnName,
                                    ["adminOnly"] = true
                                });
                            }
                        }
                        break;
                }
            }
            catch (Exception ex)
            {
                LogUtil.Error($"Error processing relay message: {ex.Message}");
            }
        }

        private void HandleViewerJoined(string json)
        {
            string username = JsonHelper.ExtractString(json, "username");
            string displayName = JsonHelper.ExtractString(json, "displayName") ?? username;
            if (username == null) return;

            var session = viewerManager.GetOrCreateSession(username, displayName);
            session?.SetMapTransportPreference(JsonHelper.ExtractString(json, "mapTransport"));
            LogUtil.Log($"Viewer joined: {displayName} ({username})");

            // Returning viewers get their previous colonist back automatically.
            // This re-establishes a pairing the streamer already approved (see
            // ViewerManager.TryReconnectPreviousPawn) rather than granting
            // anything new, so it does not need a fresh approval prompt — and it
            // must run BEFORE the "waiting for a colonist" alert below, or the
            // streamer gets pinged about a viewer who was just reconnected.
            if (session != null && !session.OwnsPawn
                && OverlordMod.Settings?.autoReconnectPreviousPawn != false)
            {
                var restored = viewerManager.TryReconnectPreviousPawn(username);
                if (restored != null)
                {
                    Messages.Message(
                        $"[Overlord] {displayName} reconnected to {restored.LabelShort}.",
                        restored, MessageTypeDefOf.NeutralEvent, historical: false
                    );
                }
            }

            viewerManager.SendColonistList(username);
            SendHostCapabilities(username);
            SendMapTransportSelection(username, session);
            viewerManager.SendPermissions(username);
            // Force game_info so late joiners don't stay stuck on "Host waiting".
            viewerManager.SendGameInfoNow(username);

            // Alert the streamer only when the viewer genuinely OWNS no colonist.
            // A pawn that's merely off-map (downed & carried, caravan, pod, captured,
            // cryptosleep) is NOT lost — ownership persists and control resumes when
            // it respawns, so the "needs a colonist" pop-up must not fire for it.
            if (session != null && session.isConnected && !session.OwnsPawn
                && viewerManager.GetPendingClaim(username) == null)
            {
                ClaimAlertOverlay.NotifyWaitingViewer(session);
                Messages.Message(
                    $"[Overlord] {displayName} is waiting for a colonist.",
                    MessageTypeDefOf.NeutralEvent,
                    historical: false
                );
            }
        }

        // Per-viewer, per-request-type rate floor. These request types skip
        // PawnCommandRouter, so its command cooldown never covered them, and the relay
        // throttles nothing but context_menu — a client loop (or a hand-written socket
        // message) could drive unbounded main-thread work. Keyed "type|username" so a
        // viewer spamming one request cannot starve another type.
        //
        // Admin/host requests (no username) are never floored: the admin page needs an
        // immediate, correct answer when it opens.
        private readonly Dictionary<string, int> lastRequestTick = new Dictionary<string, int>();
        private const int ColonistListMinTicks = 120; // 2 seconds

        private bool ShouldServeRequest(string requestType, string username, int minTicks)
        {
            if (string.IsNullOrEmpty(username))
                return true;
            string key = requestType + "|" + username;
            int now = Find.TickManager?.TicksGame ?? 0;
            if (lastRequestTick.TryGetValue(key, out int last) && now - last < minTicks)
                return false;
            lastRequestTick[key] = now;
            return true;
        }

        private bool ShouldServeColonistList(string username)
            => ShouldServeRequest("colonist_list", username, ColonistListMinTicks);

        private void HandleViewerLeft(string json)
        {
            string username = JsonHelper.ExtractString(json, "username");
            if (username == null) return;
            viewerManager?.MarkDisconnected(username);
            LogUtil.Log($"Viewer left: {username}");
        }

        private void HandleCommand(string json)
        {
            bool isAdminCommand = IsAdminMessage(json);
            string action = JsonHelper.ExtractLastString(json, "action") ?? "unknown";
            string username = JsonHelper.ExtractLastString(json, "username");
            var result = PawnCommandRouter.Execute(json, viewerManager);
            bool silent = result != null &&
                result.TryGetValue("silent", out object silentValue) &&
                silentValue is bool silentBool &&
                silentBool;
            bool ok = result != null && result.TryGetValue("ok", out object okValue) && okValue is bool okBool && okBool;
            // Commands are the only way slow-tier signature fields (work priorities,
            // schedule, policies, gear) change instantly — drop the cached slow sub-hash
            // so the next sync cycle reflects the command without waiting out the cache.
            if (ok && !string.IsNullOrEmpty(username))
                PawnStateSerializer.InvalidateSignatureCache(viewerManager?.GetSession(username)?.assignedPawn);
            string resultMessage = result != null && result.TryGetValue("message", out object messageValue)
                ? messageValue?.ToString()
                : "";
            if (result != null)
                result["action"] = action;
            if (!silent)
            {
                LogUtil.Log($"Command source={(isAdminCommand ? "admin" : "viewer")} user={username ?? ""} action={action} ok={ok} message={resultMessage}");
                if (!isAdminCommand && !string.IsNullOrEmpty(username))
                {
                    ActionLog.Append(
                        ok ? ActionLogKind.Command : ActionLogKind.CommandFailed,
                        username, action, resultMessage,
                        viewerManager?.GetSession(username)?.assignedPawn?.thingIDNumber);
                }
            }

            if (isAdminCommand && !silent)
            {
                var adminResult = new Dictionary<string, object>(result)
                {
                    ["adminOnly"] = true,
                    ["username"] = username ?? ""
                };
                relayClient?.Broadcast(adminResult);
            }

            if (silent || string.IsNullOrEmpty(username)) return;

            SendToViewer(username, result);
        }

        private void HandleRequestState(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            if (username == null) return;
            HandleRequestStatePublic(username);
        }

        private void HandleMapTransport(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            if (string.IsNullOrEmpty(username))
                return;

            var session = viewerManager?.GetSession(username);
            if (session == null)
                return;

            session.SetMapTransportPreference(JsonHelper.ExtractString(json, "transport"));
            SendMapTransportSelection(username, session);
            if (session.UsesTacticalMapTransport && session.HasPawn)
                viewerManager.SendTacticalMapSnapshot(username);
        }

        private void SendMapTransportSelection(string username, ViewerSession session)
        {
            if (string.IsNullOrEmpty(username) || session == null)
                return;

            SendToViewer(username, new Dictionary<string, object>
            {
                ["type"] = StateProtocol.MapTransport,
                ["requested"] = session.RequestedMapTransport,
                ["selected"] = session.SelectedMapTransport,
                ["tileAvailable"] = session.TacticalMapTransportAvailable,
                ["jpegAvailable"] = true
            });
        }

        private void HandleRequestArmory(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            if (string.IsNullOrEmpty(username))
                return;

            int requestId = JsonHelper.ExtractInt(json, "requestId", 0);
            var session = viewerManager?.GetSession(username);
            Dictionary<string, object> response;
            if (session == null || !session.HasPawn)
            {
                response = ArmoryCatalog.BuildResponse(
                    null, requestId, "", "all", "distance", 0, 3);
            }
            else if (!session.permissions.IsAllowed(StateProtocol.CmdEquip))
            {
                response = new Dictionary<string, object>
                {
                    ["type"] = StateProtocol.ArmoryState,
                    ["ok"] = false,
                    ["requestId"] = requestId,
                    ["message"] = "The streamer disabled equipment changes",
                    ["items"] = new List<Dictionary<string, object>>()
                };
            }
            else
            {
                response = ArmoryCatalog.BuildResponse(
                    session.assignedPawn,
                    requestId,
                    JsonHelper.ExtractString(json, "search"),
                    JsonHelper.ExtractString(json, "slot"),
                    JsonHelper.ExtractString(json, "sort"),
                    JsonHelper.ExtractInt(json, "page", 0),
                    JsonHelper.ExtractInt(json, "pageSize", 3));
            }
            SendToViewer(username, response);
        }

        // Client requests item icons on demand (never pushed). "defs" is a
        // comma-separated list of keys: "defName" or "defName|stuffDefName".
        // Icons are static, so once cached they cost nothing. Capped per request
        // so a malformed client can't force a huge render batch on the main thread.
        private const int MaxIconsPerRequest = 60;

        private void HandleRequestIcons(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            if (string.IsNullOrEmpty(username))
                return;

            string defsCsv = JsonHelper.ExtractString(json, "defs");
            if (string.IsNullOrEmpty(defsCsv))
                return;

            // Answer already-cached icons immediately (a Dictionary lookup, no
            // render). Queue only the uncached ones — the actual GPU-stalling
            // render happens a few per frame in ProcessIconQueue, so a burst of
            // requests from several viewers can't hitch the streamer's game.
            var cached = new Dictionary<string, object>();
            int queued = 0;
            foreach (string rawKey in defsCsv.Split(','))
            {
                string key = rawKey?.Trim();
                if (string.IsNullOrEmpty(key))
                    continue;
                if (queued >= MaxIconsPerRequest)
                    break;

                if (iconCache.TryGetValue(key, out string b64))
                {
                    if (!string.IsNullOrEmpty(b64) && !cached.ContainsKey(key))
                        cached[key] = b64;
                    continue;
                }

                string pendKey = username + ":" + key;
                if (pendingIconKeys.Add(pendKey))
                {
                    iconQueue.Enqueue(new IconRequest { username = username, key = key });
                    queued++;
                }
            }

            if (cached.Count > 0)
                SendToViewer(username, new Dictionary<string, object>
                {
                    ["type"] = StateProtocol.ItemIcons,
                    ["icons"] = cached
                });
        }

        // Render a bounded number of queued icons per frame (each is a GPU ReadPixels
        // stall). Groups the frame's finished icons per viewer into one message.
        private void ProcessIconQueue()
        {
            if (iconQueue.Count == 0)
                return;

            Dictionary<string, Dictionary<string, object>> perViewer = null;
            int rendered = 0;
            while (iconQueue.Count > 0 && rendered < IconsRenderedPerFrame)
            {
                var req = iconQueue.Dequeue();
                pendingIconKeys.Remove(req.username + ":" + req.key);

                if (!iconCache.TryGetValue(req.key, out string b64))
                {
                    string[] parts = req.key.Split('|');
                    ThingDef def = DefDatabase<ThingDef>.GetNamedSilentFail(parts[0]);
                    ThingDef stuff = parts.Length > 1 && !string.IsNullOrEmpty(parts[1])
                        ? DefDatabase<ThingDef>.GetNamedSilentFail(parts[1])
                        : null;
                    b64 = IconRenderer.GetIconBase64(def, stuff) ?? "";
                    iconCache[req.key] = b64;
                    rendered++;
                }

                if (string.IsNullOrEmpty(b64))
                    continue;

                if (perViewer == null)
                    perViewer = new Dictionary<string, Dictionary<string, object>>();
                if (!perViewer.TryGetValue(req.username, out var icons))
                {
                    icons = new Dictionary<string, object>();
                    perViewer[req.username] = icons;
                }
                icons[req.key] = b64;
            }

            if (perViewer == null)
                return;
            foreach (var pair in perViewer)
                SendToViewer(pair.Key, new Dictionary<string, object>
                {
                    ["type"] = StateProtocol.ItemIcons,
                    ["icons"] = pair.Value
                });
        }

        // Colony roster: all free colonists with basic identity + significant
        // relations, for the viewer's "who is everyone" window. On-demand only
        // (fires when a viewer opens the window) — no per-tick cost.
        private void HandleRequestRoster(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            if (string.IsNullOrEmpty(username))
                return;

            var rows = new List<Dictionary<string, object>>();
            var maps = Find.Maps;
            if (maps != null)
            {
                foreach (var map in maps)
                {
                    if (map?.mapPawns == null || !map.IsPlayerHome && map != Find.CurrentMap)
                        continue;
                    foreach (var p in map.mapPawns.FreeColonists)
                    {
                        if (p == null || p.Dead) continue;
                        if (rows.Count >= 60) break;

                        var rels = new List<string>();
                        try
                        {
                            var direct = p.relations?.DirectRelations;
                            if (direct != null)
                            {
                                foreach (var rel in direct)
                                {
                                    if (rel?.def == null || rel.otherPawn == null || rel.otherPawn.Dead) continue;
                                    if (rels.Count >= 6) break;
                                    rels.Add($"{rel.def.label ?? rel.def.defName}: {rel.otherPawn.LabelShort}");
                                }
                            }
                        }
                        catch { }

                        string viewer = null;
                        try { viewer = viewerManager?.GetSessionForPawn(p)?.displayName; } catch { }

                        rows.Add(new Dictionary<string, object>
                        {
                            ["id"] = p.thingIDNumber,
                            ["name"] = p.LabelShort ?? "colonist",
                            ["gender"] = p.gender.ToString(),
                            ["age"] = p.ageTracker?.AgeBiologicalYears ?? 0,
                            ["relations"] = rels,
                            ["viewer"] = viewer,
                        });
                    }
                }
            }

            SendToViewer(username, new Dictionary<string, object>
            {
                ["type"] = StateProtocol.RosterState,
                ["colonists"] = rows
            });
        }

        // Chat prints ATTACKER-CONTROLLED TEXT into the streamer's own game window and
        // broadcasts it to every viewer, and it is dispatched straight from
        // OnRelayMessage — so PawnCommandRouter's cooldown never applied and there was
        // no length cap. One viewer could wallpaper the HUD (Verse.Messages keeps 12
        // live and each re-arms a 13s timer) or push a wall of text to everyone.
        private const int MaxChatLength = 240;
        private const int ChatMinTicks = 90; // ~1.5s between messages per viewer

        private void HandleChat(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            string message = JsonHelper.ExtractString(json, "message");
            if (string.IsNullOrEmpty(username) || string.IsNullOrEmpty(message)) return;

            if (!ShouldServeRequest("chat", username, ChatMinTicks))
                return;

            // Collapse newlines and control characters — a multi-line payload turns one
            // message into many visual lines in the streamer's HUD — then hard-cap it.
            var cleaned = new System.Text.StringBuilder(Math.Min(message.Length, MaxChatLength));
            foreach (char c in message)
            {
                if (cleaned.Length >= MaxChatLength) break;
                cleaned.Append(char.IsControl(c) ? ' ' : c);
            }
            message = cleaned.ToString().Trim();
            if (message.Length == 0) return;

            // Show in-game as a message
            Messages.Message(
                $"[{username}] {message}",
                MessageTypeDefOf.NeutralEvent,
                historical: false
            );

            // Broadcast to all viewers
            var chatMsg = new Dictionary<string, object>
            {
                ["type"] = "chat",
                ["username"] = username,
                ["message"] = message
            };
            relayClient?.Broadcast(chatMsg);
            embeddedServer?.Broadcast(JsonHelper.ToJson(chatMsg));
        }

        public void HandleRequestStatePublic(string username)
        {
            var session = viewerManager.GetSession(username);
            // Always refresh host clock/speed for this viewer, even before assignment.
            viewerManager?.SendGameInfoNow(username);
            if (session == null || !session.HasPawn) return;

            // Fresh slow-tier hash so lastStateHash matches the serialized payload.
            PawnStateSerializer.InvalidateSignatureCache(session.assignedPawn);
            var stateJson = PawnStateSerializer.Serialize(session.assignedPawn);
            int signature = PawnStateSerializer.ComputeStateSignature(session.assignedPawn);
            viewerManager.SendPermissions(username);

            // Same rule as the Tick sender: only claim the viewer has this state once a
            // transport accepted it. Storing the hash for a dropped message strands them.
            if (SendToViewer(username, StateProtocol.BuildPawnStateMessage(session, stateJson)))
                session.lastStateHash = signature;

            QueuePawnPortrait(username, session.assignedPawn);
            viewerManager.SendTacticalMapSnapshot(username);
            viewerManager.SendResourceReadout(username, force: true);
        }

        private void QueuePawnPortrait(string username, Pawn pawn)
        {
            if (string.IsNullOrEmpty(username) || pawn == null || pawn.Dead || pawn.Destroyed)
                return;

            int pawnId = pawn.thingIDNumber;
            if (portraitCache.TryGetValue(pawnId, out string cachedPortrait))
            {
                SendPortrait(username, cachedPortrait);
                return;
            }

            string key = username + ":" + pawnId;
            if (pendingPortraitKeys.Contains(key))
                return;

            pendingPortraitKeys.Add(key);
            portraitQueue.Enqueue(new PortraitRequest
            {
                username = username,
                pawn = pawn,
                pawnId = pawnId,
                key = key
            });
        }

        private void ProcessPortraitQueue()
        {
            if (portraitQueue.Count == 0)
                return;

            float now = UnityEngine.Time.realtimeSinceStartup;
            if (now < nextPortraitTime)
                return;
            nextPortraitTime = now + 0.5f; // process one portrait every 0.5s regardless of pause state

            var request = portraitQueue.Dequeue();
            pendingPortraitKeys.Remove(request.key);

            if (request.pawn == null || request.pawn.Destroyed || request.pawn.Dead)
                return;

            if (!portraitCache.TryGetValue(request.pawnId, out string portrait))
            {
                portrait = PortraitRenderer.GetPortraitBase64(request.pawn);
                if (!string.IsNullOrEmpty(portrait))
                    portraitCache[request.pawnId] = portrait;
            }

            if (!string.IsNullOrEmpty(portrait))
                SendPortrait(request.username, portrait);
        }

        private void SendPortrait(string username, string portrait)
        {
            SendToViewer(username, new Dictionary<string, object>
            {
                ["type"] = StateProtocol.PawnPortrait,
                ["data"] = portrait
            });
        }

        public void InvalidatePawnPortrait(Pawn pawn)
        {
            if (pawn == null)
                return;

            portraitCache.Remove(pawn.thingIDNumber);
        }

        private void HandleAssign(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            int pawnId = JsonHelper.ExtractInt(json, "pawnId", -1);
            if (username == null || pawnId < 0) return;

            var pawn = viewerManager.FindPawnById(pawnId);
            if (pawn == null)
            {
                LogUtil.Warn($"Assign failed: pawn {pawnId} not found");
                return;
            }

            if (viewerManager.GetSession(username) == null)
                viewerManager.GetOrCreateSession(username, username);

            if (viewerManager.AssignPawn(username, pawn))
            {
                viewerManager.SendColonistList();
                HandleRequestState(json);
            }
        }

        private void HandleUnassign(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            if (username == null) return;

            viewerManager.UnassignPawn(username);
            viewerManager.SendColonistList();
        }

        private void HandleClaimResponse(string json)
        {
            string username = JsonHelper.ExtractLastString(json, "username");
            bool approved = JsonHelper.ExtractBool(json, "approved", false);
            if (string.IsNullOrEmpty(username)) return;

            if (approved)
            {
                int pawnId = JsonHelper.ExtractInt(json, "pawnId", -1);
                var pawn = viewerManager.FindPawnById(pawnId);
                if (viewerManager.GetSession(username) == null)
                    viewerManager.GetOrCreateSession(username, username);
                if (pawn != null && viewerManager.AssignPawn(username, pawn))
                {
                    viewerManager.SendColonistList();
                    HandleRequestStatePublic(username);
                }
            }
            else
            {
                viewerManager.RejectClaim(username);
                viewerManager.SendColonistList();
            }
        }

        private static bool IsAdminMessage(string json)
        {
            return JsonHelper.ExtractLastBool(json, "adminCommand", false) &&
                   JsonHelper.ExtractLastString(json, "source") == "admin";
        }

        /// <summary>
        /// Returns TRUE only if at least one transport actually accepted the message.
        /// Callers that commit change-detection state must gate on this: a dropped
        /// message with the hash already stored leaves the viewer stale until the
        /// state changes AGAIN, which for a mostly-idle pawn can be a long time.
        /// </summary>
        private bool SendToViewer(string username, Dictionary<string, object> msg)
        {
            string json = JsonHelper.ToJson(msg);
            bool relayOk = relayClient?.SendToViewer(username, msg) ?? false;
            bool embeddedOk = embeddedServer?.SendToViewer(username, json) ?? false;
            return relayOk || embeddedOk;
        }

        public bool SendToViewerPublic(string username, Dictionary<string, object> msg)
        {
            return SendToViewer(username, msg);
        }

        // Store rebuilds are expensive AND were completely invisible: the toolkit_refresh
        // command returns silent=true so HandleCommand skips its log line, and this
        // method logged nothing either. That invisibility is what produced a wrong
        // conclusion on 2026-08-04 — a constantly-firing host action left no trace, and
        // the absence of log lines was read as absence of the event. Only the client
        // trigger was throttled afterwards; the blindness itself is fixed here.
        // Logged when the rebuild is slow enough to matter, so a healthy stream stays
        // quiet but a pathological one names itself.
        private const long ToolkitStateSlowMs = 20;

        public void SendToolkitStatePublic(string username)
        {
            if (string.IsNullOrEmpty(username))
                return;
            var watch = System.Diagnostics.Stopwatch.StartNew();
            var state = TwitchToolkitBridge.BuildViewerState(username);
            watch.Stop();
            if (watch.ElapsedMilliseconds >= ToolkitStateSlowMs)
            {
                int entryCount = state != null && state.TryGetValue("entries", out object e) && e is System.Collections.ICollection c
                    ? c.Count : -1;
                LogUtil.Log($"Toolkit store rebuild for {username} took {watch.ElapsedMilliseconds}ms ({entryCount} entries)");
            }
            SendToViewer(username, state);
        }

        private void SendHostCapabilities(string username = null, bool adminOnly = false)
        {
            var msg = RimWorldCompat.BuildCapabilityMessage();
            if (adminOnly)
            {
                msg["adminOnly"] = true;
                relayClient?.Broadcast(msg);
                return;
            }

            if (!string.IsNullOrEmpty(username))
            {
                SendToViewer(username, msg);
                return;
            }

            relayClient?.Broadcast(msg);
            embeddedServer?.Broadcast(JsonHelper.ToJson(msg));
        }

        public void OnPawnKilled(Pawn pawn)
        {
            viewerManager?.OnPawnKilled(pawn);
        }

        public void NotifyClaimRequest(PendingClaim claim)
        {
            ClaimAlertOverlay.NotifyClaimRequest(claim);
        }

        public RelayClient Relay => relayClient;
        public ViewerManager Viewers => viewerManager;
        public EmbeddedWebServer EmbeddedServer => embeddedServer;
        public bool IsInitialized => initialized;

        private VoteManager voteManager = new VoteManager();
        public VoteManager VoteManager => voteManager;
    }
}
